default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shoper_development

test:
  <<: *default
  database: shoper_test

production:
  <<: *default
  database: shoper_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
